version: '3.4'

services:
    db:
      image: postgres:14.6
      restart: always
      environment:
        - POSTGRES_USER=blog_dev_user
        - POSTGRES_PASSWORD=2770562as
      

      ports:
        - 5432:5432

